version: '3'

services:
  forrajeria-dashboard-v1:
    image: 330121144853.dkr.ecr.us-east-2.amazonaws.com/forrajeria-dashboard-v1:latest
    container_name: forrajeria-dashboard-v1
    restart: unless-stopped
    networks:
      - default
    environment:
      - VIRTUAL_HOST=forrajera-dashboard-testing.paramq.com
      - LETSENCRYPT_HOST=forrajera-dashboard-testing.paramq.com
      - VIRTUAL_PORT=80
networks:
  default:
    external:
      name: net-proxy